handler: lib/EGKApi.js#EGKApi
appname: EGKApi
servicename: EGK
libs:
    - 'core@1.x'
    - 'dl@1.x'
    - 'async@2.0.1'
    - 'nock@0.59.1'
    - 'xml2json@0.9.0'
    - 'follow-redirects@0.2.0'
    - 'jayson@2.0.5'
    - 'demon@1.4.4'
sdk_version: node_0.8.28.1
version: "1.0"
interfaces:
    drugsearch:
        authentication: false
        authorisation: false
        ssl: false
    geturl:
        authentication: false
        authorisation: false
        ssl: false
